spring:
  datasource:
    username: root
    password: 166414
    url: jdbc:mysql://localhost:3306/master_slave_replication_db?serverTimezone=GMT&useSSL=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatement=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
  #  When implementing file upload, do not use Spring's default StandardServletMultipartResolver, instead use CommonsMultipartResolver that commons-fileupload depends on
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration

  #  Configure redis remote connection
  redis:
    host: 192.168.198.10

  #  Configure view resolvers
  mvc:
    view:
      prefix: /
      suffix: .html
#    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.zhangweijie.pojo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
